/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author zoyamahmood
 */
public class AddStudentDetails extends javax.swing.JFrame {

    /**
     * Creates New Form AddStudentDetails
     */
    public AddStudentDetails() {
        initComponents();
    }
public javax.swing.JTextField getTfFirstName() {
        return TfFirstName;
    }

    public javax.swing.JTextField getTfLastName() {
        return TfLastName;
    }

    public javax.swing.JTextField getTfPrefName() {
        return TfPrefName;
    }

    public javax.swing.JTextField getTfStudID() {
        return TfStudID;
    }

    public javax.swing.JList<String> getLstGender() {
        return LstGender;
    }

    public javax.swing.JTextField getTfEmail() {
        return TfEmail;
    }

    public javax.swing.JTextField getTfDOB() {
        return TfDOB;
    }

    public javax.swing.JTextField getTfAddress() {
        return TfAddress;
    }

    public javax.swing.JTextField getTfSuburb() {
        return TfSuburb;
    }

    public javax.swing.JTextField getTfCity() {
        return TfCity;
    }

    public javax.swing.JTextField getTfPostCode() {
        return TfPostCode;
    }

    public javax.swing.JTextField getTfPhone() {
        return TfPhone;
    }

    public javax.swing.JButton getBtnSubmit() {
        return BtnSubmit;
    }

    public javax.swing.JButton getBtnClear() {
        return BtnClear;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstGender = new javax.swing.JList<>();
        TfFirstName = new javax.swing.JTextField();
        TfLastName = new javax.swing.JTextField();
        TfPrefName = new javax.swing.JTextField();
        TfStudID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabelS = new javax.swing.JLabel();
        jLabelC = new javax.swing.JLabel();
        jLabelP = new javax.swing.JLabel();
        TfCity = new javax.swing.JTextField();
        TfDOB = new javax.swing.JTextField();
        TfSuburb = new javax.swing.JTextField();
        TfAddress = new javax.swing.JTextField();
        TfPostCode = new javax.swing.JTextField();
        BtnSubmit = new javax.swing.JButton();
        TfPhone = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnClear = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();
        BtnHome1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(790, 597));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 597));
        jPanel1.setSize(new java.awt.Dimension(790, 597));

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter New Student Details");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(208, 244, 244));
        jLabel2.setText("* First Name: ");

        jLabel3.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(208, 244, 244));
        jLabel3.setText("* Last Name:");

        jLabel4.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(208, 244, 244));
        jLabel4.setText("Preferred First Name: (if applicable)");

        jLabel5.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(208, 244, 244));
        jLabel5.setText("* Student ID:");

        jLabel6.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(208, 244, 244));
        jLabel6.setText("* Gender:");

        LstGender.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        LstGender.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Male", "Female", "Non-binary", "Prefer not to say", "Other" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(LstGender);

        TfFirstName.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        TfFirstName.setSize(new java.awt.Dimension(80, 23));
        TfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfFirstNameActionPerformed(evt);
            }
        });

        TfLastName.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        TfLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfLastNameActionPerformed(evt);
            }
        });

        TfPrefName.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        TfStudID.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(208, 244, 244));
        jLabel7.setText("*Date of Birth (DD-MM-YYYY):");

        jLabel.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel.setForeground(new java.awt.Color(208, 244, 244));
        jLabel.setText("*Address: (Number & Street)");

        jLabelS.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabelS.setForeground(new java.awt.Color(208, 244, 244));
        jLabelS.setText("*Suburb:");

        jLabelC.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabelC.setForeground(new java.awt.Color(208, 244, 244));
        jLabelC.setText("*City:");

        jLabelP.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabelP.setForeground(new java.awt.Color(208, 244, 244));
        jLabelP.setText("*Post Code:");

        TfCity.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        TfDOB.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        TfDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfDOBActionPerformed(evt);
            }
        });

        TfSuburb.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        TfSuburb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfSuburbActionPerformed(evt);
            }
        });

        TfAddress.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        TfPostCode.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        TfPostCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPostCodeActionPerformed(evt);
            }
        });

        BtnSubmit.setBackground(new java.awt.Color(2, 154, 154));
        BtnSubmit.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 13)); // NOI18N
        BtnSubmit.setForeground(new java.awt.Color(208, 244, 244));
        BtnSubmit.setText("SUBMIT");
        BtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSubmitActionPerformed(evt);
            }
        });

        TfPhone.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        TfEmail.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(208, 244, 244));
        jLabel8.setText("*Phone Number:");

        jLabel9.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(208, 244, 244));
        jLabel9.setText("* Email Address:");

        BtnClear.setBackground(new java.awt.Color(2, 154, 154));
        BtnClear.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 13)); // NOI18N
        BtnClear.setForeground(new java.awt.Color(208, 244, 244));
        BtnClear.setText("CLEAR");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        BtnHome.setBackground(new java.awt.Color(2, 154, 154));
        BtnHome.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 11)); // NOI18N
        BtnHome.setForeground(new java.awt.Color(208, 244, 244));
        BtnHome.setText("Back Home");
        BtnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        BtnHome1.setBackground(new java.awt.Color(2, 154, 154));
        BtnHome1.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 11)); // NOI18N
        BtnHome1.setForeground(new java.awt.Color(208, 244, 244));
        BtnHome1.setText("View");
        BtnHome1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnHome1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TfEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfStudID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfPrefName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(TfFirstName, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel)
                            .addComponent(jLabelP)
                            .addComponent(jLabelC)
                            .addComponent(jLabelS)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TfPhone)
                            .addComponent(TfPostCode)
                            .addComponent(TfCity)
                            .addComponent(TfSuburb)
                            .addComponent(TfAddress)
                            .addComponent(TfDOB)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(BtnHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(BtnHome)
                    .addComponent(BtnHome1))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(TfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelS)
                                    .addComponent(jLabel4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfPrefName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfStudID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TfPostCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfSuburb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabelC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfFirstNameActionPerformed

    private void TfPostCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPostCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPostCodeActionPerformed

    private void TfSuburbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfSuburbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfSuburbActionPerformed

    private void BtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSubmitActionPerformed
        String firstName = TfFirstName.getText();
        String lastName = TfLastName.getText();
        String prefName = TfPrefName.getText();
        String studID = TfStudID.getText();
        String gender = LstGender.getSelectedValue();
        String email = TfEmail.getText();
        String DOB = TfDOB.getText();
        String address = TfAddress.getText();
        String suburb = TfSuburb.getText();
        String city = TfCity.getText();
        String postCode = TfPostCode.getText();
        String phone = TfPhone.getText();
        

        if (firstName.isEmpty() || lastName.isEmpty() || studID.isEmpty() || gender == null || DOB.isEmpty() || address.isEmpty() || suburb.isEmpty() || city.isEmpty() || postCode.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
            // Database connection parameters
    String url = "jdbc:derby://localhost:1527/SMS";
    String sql = "INSERT INTO Student_Details (student_id, first_name, last_name, preferred_name, gender, dob, address, suburb, city, postcode, email, phone) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try (Connection conn = DriverManager.getConnection(url);
         PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, studID);
        pstmt.setString(2, firstName);
        pstmt.setString(3, lastName);
        pstmt.setString(4, prefName.isEmpty() ? null : prefName); // Preferred name can be empty
        pstmt.setString(5, gender);
        pstmt.setDate(6, convertToDate(DOB));
        pstmt.setString(7, address);
        pstmt.setString(8, suburb);
        pstmt.setString(9, city);
        pstmt.setString(10, postCode);
        pstmt.setString(11, email);
        pstmt.setString(12, phone);

        // Insert statement
        int rowsInserted = pstmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Data saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error saving data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "Error parsing date: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

private java.sql.Date convertToDate(String dateStr) throws ParseException {
    SimpleDateFormat format = new SimpleDateFormat("DD-MM-YYYY");
    java.util.Date parsedDate = format.parse(dateStr);
    return new java.sql.Date(parsedDate.getTime());

    }//GEN-LAST:event_BtnSubmitActionPerformed

    private void TfDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfDOBActionPerformed

    private void TfLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfLastNameActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        
        TfFirstName.setText("");
        TfLastName.setText("");
        TfPrefName.setText("");
        TfStudID.setText("");
        LstGender.clearSelection();
        TfEmail.setText("");
        TfDOB.setText("");
        TfAddress.setText("");
        TfSuburb.setText("");
        TfCity.setText("");
        TfPostCode.setText("");
        TfPhone.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
       new MainMenu().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHome1ActionPerformed
        new ViewStudentDetails().setVisible(true);
    }//GEN-LAST:event_BtnHome1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddStudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnHome1;
    private javax.swing.JButton BtnSubmit;
    private javax.swing.JList<String> LstGender;
    private javax.swing.JTextField TfAddress;
    private javax.swing.JTextField TfCity;
    private javax.swing.JTextField TfDOB;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfFirstName;
    private javax.swing.JTextField TfLastName;
    private javax.swing.JTextField TfPhone;
    private javax.swing.JTextField TfPostCode;
    private javax.swing.JTextField TfPrefName;
    private javax.swing.JTextField TfStudID;
    private javax.swing.JTextField TfSuburb;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelC;
    private javax.swing.JLabel jLabelP;
    private javax.swing.JLabel jLabelS;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
